//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgitimPlatformu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icerikler
    {
        public int IcerikId { get; set; }
        public string IcerikAd { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> GonderimTarihi { get; set; }
        public Nullable<int> KonuId { get; set; }
        public Nullable<int> AnlatimSekliId { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        public virtual AnlatimSekilleri AnlatimSekilleri { get; set; }
        public virtual Konular Konular { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
